### PR TITLE
Hotfix/landing illustrations

### PR DESCRIPTION
**Pull request by yowakita**
https://www.pivotaltracker.com/story/show/122205745

### CODE REVIEW

**Comment by rokimoto** [comment]
the mocks don't have the images perfectly centered, but currently some of the images get noticeably off-centered on resize

**Comment by yowakita** [comment]
@rokimoto  I noticed that too, it seems to be from the extra whitespace on two of the illustrations (#1 and #4)

**Comment by yowakita** [comment]
Also added in tickets:

https://www.pivotaltracker.com/story/show/122205433 - Changed to floating buttons
https://www.pivotaltracker.com/story/show/126138111 - Adds links to quickstart buttons in landing page
https://www.pivotaltracker.com/story/show/125735661 - Update Favicon
https://www.pivotaltracker.com/story/show/126147489 - Replace image in docs/guides page

**Comment by rokimoto** [comment]
i'm assuming they want the extended favicon set?
but other than that all the other tickets look good 👍

**Pull request merged**
